version: '3.1'
services:
  nodementoring:
    build: .
    image: node-mentoring
    ports:
      - "8080:8080"
    depends_on:
      - postgres-nodeapp
    restart: always
    networks:
      - backend
  postgres-nodeapp:
    image: postgres
    restart: always
    volumes:
      - ~/Code/DB/nodementoring:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - db

networks:
  backend:

